# Generated by Django 2.1.2 on 2018-10-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicePermission',
            fields=[
                ('name', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='Name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_permission', to='services.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service permission',
                'verbose_name_plural': 'Service permissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='servicepermission',
            unique_together={('service', 'name')},
        ),
    ]
