# Generated by Django 2.1.2 on 2018-11-08 23:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('route', models.CharField(max_length=120)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.ComponentInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('site', 'route')},
        ),
    ]
