# Generated by Django 2.1.2 on 2018-11-08 23:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Component instance',
                'verbose_name_plural': 'Component instances',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Component type',
                'verbose_name_plural': 'Component type',
            },
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.ComponentType'),
        ),
    ]
